sonar.projectKey=finanzly
sonar.projectName=Finanzly

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.git/**, **/coverage/**

sonar.host.url=https://sonarcloud.io

# Agrega esta línea con el token que copiaste en el Paso 1:
sonar.token= token



squ_1099693acee5fab35ef34c211cbcf11a8ad881df