sonar.projectKey=finanzly
sonar.projectName=Finanzly

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.git/**, **/coverage/**

sonar.host.url=https://sonarcloud.io

# Agrega esta línea con el token que copiaste en el Paso 1:
sonar.token=125e686f0427d035d94119d6daaaf8d14174ef71



